//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volvo.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Volvo.Core.Resources.MessagesValidation", typeof(MessagesValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Data Persist.
        /// </summary>
        public static string ErrorDataPersist {
            get {
                return ResourceManager.GetString("ErrorDataPersist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id of Truck is Requerid.
        /// </summary>
        public static string IdRequerid {
            get {
                return ResourceManager.GetString("IdRequerid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture Year Greater {0}.
        /// </summary>
        public static string ManufactureYearMinLength {
            get {
                return ResourceManager.GetString("ManufactureYearMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Id of Truck is Requerid.
        /// </summary>
        public static string ModelIdRequerid {
            get {
                return ResourceManager.GetString("ModelIdRequerid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Not Exist.
        /// </summary>
        public static string ModelNotExist {
            get {
                return ResourceManager.GetString("ModelNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Yer Must Be Equal or Greater Manufacture Year.
        /// </summary>
        public static string ModelYerManufactureYearValidate {
            get {
                return ResourceManager.GetString("ModelYerManufactureYearValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paginate Greater 0.
        /// </summary>
        public static string PaginateMinZero {
            get {
                return ResourceManager.GetString("PaginateMinZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck only exist.
        /// </summary>
        public static string TruckExist {
            get {
                return ResourceManager.GetString("TruckExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck not exist.
        /// </summary>
        public static string TruckNotExist {
            get {
                return ResourceManager.GetString("TruckNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Identification Number Invalid.
        /// </summary>
        public static string VinInvalid {
            get {
                return ResourceManager.GetString("VinInvalid", resourceCulture);
            }
        }
    }
}
