// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volvo.Trucks.API.Data;

namespace Volvo.Trucks.API.Migrations
{
    [DbContext(typeof(TruckContext))]
    partial class TruckContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Volvo.Trucks.API.Models.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Model");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8132b9df-d14b-45ae-8b7f-9fe7ecaef8a0"),
                            ModelYear = 2020,
                            Name = "FH"
                        },
                        new
                        {
                            Id = new Guid("b6e9987a-d4c5-48a6-82fd-a470a135dbfa"),
                            ModelYear = 2020,
                            Name = "FM"
                        },
                        new
                        {
                            Id = new Guid("a6f734da-f964-41f7-b2c5-1f71f0baba47"),
                            ModelYear = 2019,
                            Name = "FH"
                        },
                        new
                        {
                            Id = new Guid("b708de2e-85dc-418a-85e0-0fabfe2c7903"),
                            ModelYear = 2019,
                            Name = "FM"
                        });
                });

            modelBuilder.Entity("Volvo.Trucks.API.Models.Truck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("int");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Truck");
                });

            modelBuilder.Entity("Volvo.Trucks.API.Models.Truck", b =>
                {
                    b.HasOne("Volvo.Trucks.API.Models.Model", "Model")
                        .WithMany("Trucks")
                        .HasForeignKey("ModelId")
                        .IsRequired();

                    b.OwnsOne("Volvo.Core.DomainObject.Vin", "VIN", b1 =>
                        {
                            b1.Property<Guid>("TruckId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("varchar(17)")
                                .HasMaxLength(17);

                            b1.HasKey("TruckId");

                            b1.ToTable("Truck");

                            b1.WithOwner()
                                .HasForeignKey("TruckId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
